[default.extend-words]
mosquitto = "mosquitto"
HASS = "HASS"
Juni = "Juni"
bck = "bck"
Automations = "Automations"
automations = "automations"
ws = "ws"
WS = "WS"
ro = "ro"
hd = "hd"
dur = "dur"
pn = "pn"
Derivated = "Derivated"
Bre = "Bre"
BRIN = "BRIN"

[type.po]
extend-glob = ["*.po"]
check-file = false

[files]
extend-exclude = [
    "*.json.example",
    # French translated dashboards
    "grafana/dashboards/fr/*.json",
    "grafana/dashboards/internal/fr/*.json",
    "grafana/dashboards/reports/fr/*.json",
    # Production docker-compose with French comments
    "docker-compose.prod.yml",
]
